modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/queekusme/Pizza-Chef/issues"

license="MIT"

[[mods]]
    modId="pizzachef"
    version="${mod_version}"
    displayName="Pizza Chef"
    displayURL="https://github.com/queekusme/Pizza-Chef/"
    authors="queekusme"
    logoFile="logo.png"
    description='Bake Delicious Pizzas for your Zombie and Creeper Friends'

    [[dependencies.pizzachef]]
        modId="forge"
        mandatory=true
        versionRange="${forge_version_range}"
        ordering="NONE"
        side="BOTH"

    [[dependencies.pizzachef]]
        modId="minecraft"
        mandatory=true
        versionRange="${minecraft_version_range}"
        ordering="NONE"
        side="BOTH"
