modLoader="javafml"
loaderVersion="[36,)"

license="MIT"

[[mods]]
    modId="pizzachef"
    version="${file.jarVersion}"
    displayName="Pizza Chef"
    authors="queekusme"
    description='Bake Delicious Pizzas for your Zombie and Creeper Friends'

    [[dependencies.pizzachef]]
        modId="forge"
        mandatory=true
        versionRange="[36,)"
        ordering="NONE"
        side="BOTH"

    [[dependencies.pizzachef]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5,1.17)"
        ordering="NONE"
        side="BOTH"
