# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
---
name: Nightly Builds

on:
  workflow_dispatch:
  # schedule:
    # - cron: "0 2 * * *"

env:
  CURSEFORGE_API_UPLOAD: ${{ secrets.CURSEFORGE_API_UPLOAD }}
  GITHUB_ACTIONS_NIGHTLY: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Get commits in last 24 hours"
      id: commit_count
      run: echo ::set-output name=commits_in_last_24::$(git rev-list --count HEAD --not $(git rev-list -n1 --before="24 hours" --first-parent HEAD))

    - name: Set up JDK 1.8
      if: steps.commit_count.outputs.commits_in_last_24 != '0'
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Update Release Type for Nightly
      if: steps.commit_count.outputs.commits_in_last_24 != '0'
      run: sed -i -e 's/curseforge_release_type=\w*/curseforge_release_type=alpha/g' gradle.properties

    - name: Grant execute permission for gradlew
      if: steps.commit_count.outputs.commits_in_last_24 != '0'
      run: chmod +x gradlew
    - name: Build with Gradle
      if: steps.commit_count.outputs.commits_in_last_24 != '0'
      run: ./gradlew curseforge
